FROM python:3.8
#WORKDIR /opt/src
#RUN pip install --upgrade pip
#VOLUME /home/parser/backend:/opt/src
#HEALTHCHECK --interval=5m --timeout=3s CMD ls | exit 1
#RUN pip install -r backend/parser/requirements.txt
#CMD ["python3", "backend/parser/telegram_parser.py"]

