version: '2.1'
services:
    webserver:
        image: apache/airflow:2.0.0-python3.8
        restart: always
        environment:
          - LOAD_EX=n
          - EXECUTOR=Sequential
          - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite://///home/parser/backend/parser/db/airflow.db
        volumes:
          - /home/parser/backend/parser:/usr/local/airflow/dags
        ports:
          - "8083:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "-f /usr/local/airflow/airflow-webserver.pid"]
            interval: 30s
            timeout: 30s
            retries: 3
    scheduler:
        image: apache/airflow:2.0.0-python3.8 
        restart: always
        environment:
          - LOAD_EX=n 
          - EXECUTOR=Sequential
          - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite://///home/parser/backend/parser/db/airflow.db
        depends_on:
          - webserver
        volumes:
          - /home/parser/backend/parser:/usr/local/airflow/dags
        command: scheduler
